// Autogenerated from Pigeon (v3.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_H_
#define PIGEON_MESSAGES_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

/* Generated class from Pigeon. */

class FlutterError {
 public:
  FlutterError();
  FlutterError(const std::string& arg_code) : code(arg_code){};
  FlutterError(const std::string& arg_code, const std::string& arg_message)
      : code(arg_code), message(arg_message){};
  FlutterError(const std::string& arg_code, const std::string& arg_message,
               const flutter::EncodableValue& arg_details)
      : code(arg_code), message(arg_message), details(arg_details){};
  std::string code;
  std::string message;
  flutter::EncodableValue details;
};
template <class T>
class ErrorOr {
  std::variant<std::unique_ptr<T>, T, FlutterError> v;

 public:
  ErrorOr(const T& rhs) { new (&v) T(rhs); }
  ErrorOr(const FlutterError& rhs) { new (&v) FlutterError(rhs); }
  static ErrorOr<std::unique_ptr<T>> MakeWithUniquePtr(std::unique_ptr<T> rhs) {
    ErrorOr<std::unique_ptr<T>> ret = ErrorOr<std::unique_ptr<T>>();
    ret.v = std::move(rhs);
    return ret;
  }
  bool hasError() const { return std::holds_alternative<FlutterError>(v); }
  const T& value() const { return std::get<T>(v); };
  const FlutterError& error() const { return std::get<FlutterError>(v); };

 private:
  ErrorOr() = default;
  friend class ErrorOr;
};

/* Generated class from Pigeon that represents data sent in messages. */
class RequestInfoMessage {
 public:
  RequestInfoMessage();
  const flutter::EncodableMap* request_data() const;
  void set_request_data(const flutter::EncodableMap* value_arg);
  void set_request_data(const flutter::EncodableMap& value_arg);

 private:
  RequestInfoMessage(flutter::EncodableMap map);
  flutter::EncodableMap ToEncodableMap() const;
  friend class SamsungCheckoutApi;
  friend class SamsungCheckoutApiCodecSerializer;
  std::optional<flutter::EncodableMap> request_data_;
};

class SamsungCheckoutApiCodecSerializer
    : public flutter::StandardCodecSerializer {
 public:
  inline static SamsungCheckoutApiCodecSerializer& GetInstance() {
    static SamsungCheckoutApiCodecSerializer sInstance;
    return sInstance;
  }

  SamsungCheckoutApiCodecSerializer();

 public:
  void WriteValue(const flutter::EncodableValue& value,
                  flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
      uint8_t type, flutter::ByteStreamReader* stream) const override;
};

/* Generated class from Pigeon that represents a handler of messages from
 * Flutter. */
class SamsungCheckoutApi {
 public:
  SamsungCheckoutApi(const SamsungCheckoutApi&) = delete;
  SamsungCheckoutApi& operator=(const SamsungCheckoutApi&) = delete;
  virtual ~SamsungCheckoutApi(){};
  virtual std::optional<FlutterError> SetRequestData(
      const RequestInfoMessage& msg) = 0;

  /** The codec used by SamsungCheckoutApi. */
  static const flutter::StandardMessageCodec& GetCodec();
  /** Sets up an instance of `SamsungCheckoutApi` to handle messages through the
   * `binary_messenger`. */
  static void SetUp(flutter::BinaryMessenger* binary_messenger,
                    SamsungCheckoutApi* api);
  static flutter::EncodableMap WrapError(std::string_view error_message);
  static flutter::EncodableMap WrapError(const FlutterError& error);

 protected:
  SamsungCheckoutApi() = default;
};
#endif  // PIGEON_MESSAGES_H_
